version: '3.8'

services:
  price-service:
    build:
      context: ./price-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/coinsight
    depends_on:
      - mongodb

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/coinsight
      - REDIS_URL=redis://redis:6379/0
      - RAILS_ENV=development
    depends_on:
      - postgres
      - redis

  web-dashboard:
    build:
      context: ./web-dashboard
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - API_URL=http://api-service:3000

  recommendation-engine:
    build:
      context: ./recommendation-engine
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/coinsight
    depends_on:
      - mongodb

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coinsight
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
